base and saltmaster
rbkmoney/rbkmoney-infra pull request #1
Opened 2019-09-13 15:57 UTC by a-a-abramov

2019-09-13 17:47 UTC, a-a-abramov commented
Highstate ok, ready to merge

2019-09-13 17:47 UTC, a-a-abramov commented
@vulnbe we probably need some sort of CODEOWNERS

2019-09-19 12:55 UTC, vulnbe approved these changes
Ок

2019-09-19 12:56 UTC, alexminder approved these changes

2019-09-20 09:28 UTC, niku64 requested changes

2019-09-20 09:28 UTC, niku64 commented on sls/gentoo/files/make.conf
> +USE="argon2 audit caps cgroups cracklib ecdsa efi filecaps json gnupg http2 iproute2 leaps_timezone logrotate lz4 lzma lzo multitarget netlink nettle nfsv4 nfsv41 numa openssl pcre16 sctp seccomp smp
Здесь не хватает как минимум `CPU_FLAGS_X86`. Почему бы manage-make-conf из common не использовать?

2019-09-20 09:28 UTC, niku64 commented on sls/gentoo/repos/gentoo.sls
> +{% set sync_uri = 'rsync://rsync.de.gentoo.org/gentoo-portage/' %}
Зачем здесь rsync, когда все остальное мы берем с GitHub? Предлагаю и дерево Portage брать с него.

2019-09-20 10:53 UTC, a-a-abramov commented on sls/gentoo/files/make.conf
> +USE="argon2 audit caps cgroups cracklib ecdsa efi filecaps json gnupg http2 iproute2 leaps_timezone logrotate lz4 lzma lzo multitarget netlink nettle nfsv4 nfsv41 numa openssl pcre16 sctp seccomp smp
Проблемы с построением то ли PORTAGE_BINHOST, то ли GENTOO_MIRRORS из пилларов, если url не отвечает твоим стандартам.

2019-09-20 10:53 UTC, a-a-abramov commented on sls/gentoo/repos/gentoo.sls
> +{% set sync_uri = 'rsync://rsync.de.gentoo.org/gentoo-portage/' %}
`https://github.com/gentoo/gentoo`?

2019-09-20 11:07 UTC, niku64 commented on sls/gentoo/repos/gentoo.sls
> +{% set sync_uri = 'rsync://rsync.de.gentoo.org/gentoo-portage/' %}
Отсюда: `https://github.com/gentoo-mirror/gentoo`, там с метаданными.

2019-09-20 11:39 UTC, niku64 requested changes

2019-09-20 11:39 UTC, niku64 commented on sls/gentoo/files/make.conf
> +GENTOO_MIRRORS="http://mirrors.rit.edu/gentoo/"
Может хотя бы что-то из официальных https зеркал возьмем? Или можно вообще не указывать, список по умолчанию будет.

2019-09-20 11:39 UTC, niku64 commented on sls/gentoo/files/make.conf
> +DISTDIR="/usr/portage/distfiles"
Так тоже не стоит делать, `DISTDIR` и `PORTDIR`  в `/var/tmp/` вынесены из дерева Portage.

2019-09-20 11:44 UTC, a-a-abramov commented on sls/gentoo/files/make.conf
> +DISTDIR="/usr/portage/distfiles"
Как надо?

2019-09-20 12:01 UTC, a-a-abramov commented on sls/gentoo/files/make.conf
> +DISTDIR="/usr/portage/distfiles"
Убрал обе

2019-09-20 12:01 UTC, a-a-abramov commented on sls/gentoo/files/make.conf
> +GENTOO_MIRRORS="http://mirrors.rit.edu/gentoo/"
убрал

2019-09-20 13:02 UTC, niku64 approved these changes

2019-09-20 13:02 UTC, merged